#-----------------------#
            #PLUGIN#
     #BY ItzMeFahri#
             #SUBSCRIBE#
      #CHANEL#
            #ItzMeFahri#

     #WARNING!!! JANGAN RENAME AUTHOR,HARGAILAH YANG MEMBUAT PLUGINS#
#-----------------------#


#Use \n to Line
#--------------
Title: "§e§lVANISH UI"
Content: "§r Edit to Config.yml"